"""add loans shares rd_installments activity_logs

Revision ID: 2f22563f61be
Revises: c66181755d81
Create Date: 2026-04-13 01:11:57.208206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f22563f61be'
down_revision: Union[str, Sequence[str], None] = 'c66181755d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('user_sub', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('loan_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('loan_type', sa.Enum('personal', 'emergency', 'gold', 'property', 'agriculture', 'education', name='loan_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_tenure_months', sa.Integer(), nullable=False),
    sa.Column('repayment_freq', sa.Enum('monthly', 'quarterly', 'half_yearly', 'yearly', 'bullet', name='repayment_freq_enum'), nullable=False),
    sa.Column('late_penalty_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('processing_fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('interest_rate >= 0', name='ck_loan_prod_rate_non_neg'),
    sa.CheckConstraint('late_penalty_pct >= 0', name='ck_loan_prod_penalty_non_neg'),
    sa.CheckConstraint('max_tenure_months > 0', name='ck_loan_prod_tenure_pos'),
    sa.CheckConstraint('min_amount >= 0', name='ck_loan_prod_min_non_neg'),
    sa.CheckConstraint('processing_fee_pct >= 0', name='ck_loan_prod_fee_non_neg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_loan_products_id'), 'loan_products', ['id'], unique=False)
    op.create_table('loan_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_number', sa.String(length=30), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ledger_account_id', sa.Integer(), nullable=True),
    sa.Column('applied_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sanctioned_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('disbursed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_interest_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_penalty_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('disbursed_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'approved', 'rejected', 'disbursed', 'active', 'closed', 'defaulted', name='loan_status_enum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('applied_amount > 0', name='ck_loan_applied_pos'),
    sa.CheckConstraint('outstanding_principal >= 0', name='ck_loan_outstanding_non_neg'),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_accounts_id'), 'loan_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_loan_accounts_ledger_account_id'), 'loan_accounts', ['ledger_account_id'], unique=False)
    op.create_index(op.f('ix_loan_accounts_loan_number'), 'loan_accounts', ['loan_number'], unique=True)
    op.create_index(op.f('ix_loan_accounts_member_id'), 'loan_accounts', ['member_id'], unique=False)
    op.create_index(op.f('ix_loan_accounts_product_id'), 'loan_accounts', ['product_id'], unique=False)
    op.create_table('share_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('face_value_per_share', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('total_shares >= 0', name='ck_share_total_non_neg'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_holdings_id'), 'share_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_share_holdings_member_id'), 'share_holdings', ['member_id'], unique=False)
    op.create_table('share_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.Enum('purchase', 'transfer', 'refund', 'dividend', name='share_txn_type_enum'), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_transactions_id'), 'share_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_share_transactions_member_id'), 'share_transactions', ['member_id'], unique=False)
    op.create_table('loan_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('installment_no > 0', name='ck_repay_inst_pos'),
    sa.CheckConstraint('interest_due >= 0', name='ck_repay_int_due_non_neg'),
    sa.CheckConstraint('principal_due >= 0', name='ck_repay_princ_due_non_neg'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_repayments_id'), 'loan_repayments', ['id'], unique=False)
    op.create_index(op.f('ix_loan_repayments_loan_id'), 'loan_repayments', ['loan_id'], unique=False)
    op.create_table('rd_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_account_id', sa.Integer(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount_due >= 0', name='ck_rd_amount_due_non_neg'),
    sa.CheckConstraint('installment_no > 0', name='ck_rd_inst_pos'),
    sa.ForeignKeyConstraint(['deposit_account_id'], ['deposit_accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rd_installments_deposit_account_id'), 'rd_installments', ['deposit_account_id'], unique=False)
    op.create_index(op.f('ix_rd_installments_id'), 'rd_installments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rd_installments_id'), table_name='rd_installments')
    op.drop_index(op.f('ix_rd_installments_deposit_account_id'), table_name='rd_installments')
    op.drop_table('rd_installments')
    op.drop_index(op.f('ix_loan_repayments_loan_id'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_id'), table_name='loan_repayments')
    op.drop_table('loan_repayments')
    op.drop_index(op.f('ix_share_transactions_member_id'), table_name='share_transactions')
    op.drop_index(op.f('ix_share_transactions_id'), table_name='share_transactions')
    op.drop_table('share_transactions')
    op.drop_index(op.f('ix_share_holdings_member_id'), table_name='share_holdings')
    op.drop_index(op.f('ix_share_holdings_id'), table_name='share_holdings')
    op.drop_table('share_holdings')
    op.drop_index(op.f('ix_loan_accounts_product_id'), table_name='loan_accounts')
    op.drop_index(op.f('ix_loan_accounts_member_id'), table_name='loan_accounts')
    op.drop_index(op.f('ix_loan_accounts_loan_number'), table_name='loan_accounts')
    op.drop_index(op.f('ix_loan_accounts_ledger_account_id'), table_name='loan_accounts')
    op.drop_index(op.f('ix_loan_accounts_id'), table_name='loan_accounts')
    op.drop_table('loan_accounts')
    op.drop_index(op.f('ix_loan_products_id'), table_name='loan_products')
    op.drop_table('loan_products')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
