"""fix gender enum

Revision ID: 78f8edb562d6
Revises: 40f834c537b2
Create Date: 2026-02-03 21:43:40.716282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f8edb562d6'
down_revision: Union[str, Sequence[str], None] = '40f834c537b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_profiles', sa.Column('member_id', sa.Integer(), nullable=False))
    op.add_column('member_profiles', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('member_profiles_reference_user_id_fkey'), 'member_profiles', type_='foreignkey')
    op.drop_constraint(op.f('member_profiles_location_id_fkey'), 'member_profiles', type_='foreignkey')
    op.drop_constraint(op.f('member_profiles_user_id_fkey'), 'member_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'member_profiles', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'member_profiles', 'members', ['member_id'], ['id'])
    op.drop_column('member_profiles', 'location_id')
    op.drop_column('member_profiles', 'user_id')
    op.drop_column('member_profiles', 'reference_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_profiles', sa.Column('reference_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_profiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_profiles', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member_profiles', type_='foreignkey')
    op.drop_constraint(None, 'member_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('member_profiles_user_id_fkey'), 'member_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('member_profiles_location_id_fkey'), 'member_profiles', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('member_profiles_reference_user_id_fkey'), 'member_profiles', 'users', ['reference_user_id'], ['id'])
    op.drop_column('member_profiles', 'created_by_user_id')
    op.drop_column('member_profiles', 'member_id')
    # ### end Alembic commands ###
