"""add member accounts

Revision ID: c1e90ae77e51
Revises: 46a548f002e2
Create Date: 2026-02-09 20:35:57.543931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e90ae77e51'
down_revision: Union[str, Sequence[str], None] = '46a548f002e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index(op.f('ix_member_accounts_id'), 'member_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_member_accounts_username'), 'member_accounts', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_accounts_username'), table_name='member_accounts')
    op.drop_index(op.f('ix_member_accounts_id'), table_name='member_accounts')
    op.drop_table('member_accounts')
    # ### end Alembic commands ###
