"""add schemes and deposit_accounts tables

Revision ID: c66181755d81
Revises: e4f12a7b8c90
Create Date: 2026-04-13 00:42:27.011624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66181755d81'
down_revision: Union[str, Sequence[str], None] = 'e4f12a7b8c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scheme_type', sa.Enum('fd', 'rd', 'mis', 'savings', name='scheme_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('compounding', sa.Enum('monthly', 'quarterly', 'half_yearly', 'yearly', 'on_maturity', name='compounding_enum'), nullable=False),
    sa.Column('premature_penalty_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('interest_rate >= 0', name='ck_scheme_rate_non_negative'),
    sa.CheckConstraint('max_amount IS NULL OR max_amount >= min_amount', name='ck_scheme_max_gte_min'),
    sa.CheckConstraint('min_amount >= 0', name='ck_scheme_min_non_negative'),
    sa.CheckConstraint('premature_penalty_pct >= 0', name='ck_scheme_penalty_non_negative'),
    sa.CheckConstraint('tenure_months IS NULL OR tenure_months > 0', name='ck_scheme_tenure_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_schemes_id'), 'schemes', ['id'], unique=False)
    op.create_table('deposit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('ledger_account_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_earned', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('last_interest_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'matured', 'closed', 'premature_closed', name='deposit_status_enum'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('current_balance >= 0', name='ck_deposit_balance_non_negative'),
    sa.CheckConstraint('interest_earned >= 0', name='ck_deposit_interest_non_negative'),
    sa.CheckConstraint('principal_amount >= 0', name='ck_deposit_principal_non_negative'),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_accounts_account_number'), 'deposit_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_deposit_accounts_id'), 'deposit_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_deposit_accounts_ledger_account_id'), 'deposit_accounts', ['ledger_account_id'], unique=False)
    op.create_index(op.f('ix_deposit_accounts_member_id'), 'deposit_accounts', ['member_id'], unique=False)
    op.create_index(op.f('ix_deposit_accounts_scheme_id'), 'deposit_accounts', ['scheme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deposit_accounts_scheme_id'), table_name='deposit_accounts')
    op.drop_index(op.f('ix_deposit_accounts_member_id'), table_name='deposit_accounts')
    op.drop_index(op.f('ix_deposit_accounts_ledger_account_id'), table_name='deposit_accounts')
    op.drop_index(op.f('ix_deposit_accounts_id'), table_name='deposit_accounts')
    op.drop_index(op.f('ix_deposit_accounts_account_number'), table_name='deposit_accounts')
    op.drop_table('deposit_accounts')
    op.drop_index(op.f('ix_schemes_id'), table_name='schemes')
    op.drop_table('schemes')
    # ### end Alembic commands ###
