"""fix gender enum

Revision ID: d34f24ab04d0
Revises: 78f8edb562d6
Create Date: 2026-02-03 21:44:34.010737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34f24ab04d0'
down_revision: Union[str, Sequence[str], None] = '78f8edb562d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('member_profiles_created_by_user_id_fkey'), 'member_profiles', type_='foreignkey')
    op.drop_column('member_profiles', 'created_by_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_profiles', sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('member_profiles_created_by_user_id_fkey'), 'member_profiles', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###
