# Generated by Django 5.0.6 on 2026-06-28 20:34

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheme_name', models.CharField(max_length=200)),
                ('scheme_type', models.CharField(choices=[('fd', 'Fixed Deposit'), ('rd', 'Recurring Deposit'), ('savings', 'Savings'), ('loan', 'Loan')], db_index=True, max_length=16)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual % rate', max_digits=5)),
                ('tenure', models.CharField(blank=True, help_text="e.g. '12–60 months'", max_length=100)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True, help_text='One benefit per line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schemes/', validators=[core.validators.validate_image])),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', 'scheme_name'],
                'indexes': [models.Index(fields=['scheme_type', 'is_active'], name='schemes_sch_scheme__7db4bf_idx')],
            },
        ),
    ]
