# Generated by Django 5.0.6 on 2026-06-28 20:34

import core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('attachment_pdf', models.FileField(blank=True, null=True, upload_to='notices/pdf/', validators=[core.validators.validate_document])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='notices/thumb/', validators=[core.validators.validate_image])),
                ('publish_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_important', models.BooleanField(db_index=True, default=False, help_text='Pin to top')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_important', '-publish_date'],
                'indexes': [models.Index(fields=['is_active', 'publish_date'], name='notices_not_is_acti_a5b1e2_idx')],
            },
        ),
    ]
