# Generated by Django 5.0.6 on 2026-06-29 06:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='google_map_iframe',
            field=models.TextField(blank=True, help_text='Embed <iframe> from Google Maps (only Google Maps embeds allowed)', validators=[core.validators.validate_map_iframe]),
        ),
    ]
