# Generated by Django 5.0.6 on 2026-06-28 20:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SSJD Cooperative', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', validators=[core.validators.validate_image])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', validators=[core.validators.validate_image])),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('footer_about', models.TextField(blank=True)),
                ('footer_copyright', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('head_scripts', models.TextField(blank=True)),
                ('body_scripts', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
